config/routes.rb
Rails.application.routes.draw do
  resources :writings
  root "text#text"
  get 'text/text', to: 'text#text'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/writing.rb
class Writing < ApplicationRecord
  has_one_attached :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: 'christina', password: 'thegr8', except: [:text]

end

app/controllers/text_controller.rb
class TextController < ApplicationController
  include WritingsHelper

  def text
    @writings = Writing.all
  end

end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  before_action :set_writing, only: [:show, :edit, :update, :destroy]

  # GET /writings
  # GET /writings.json


  def index
    @writings = Writing.all
  end

  # GET /writings/1
  # GET /writings/1.json
  def show
  end

  # GET /writings/new
  def new
    @writing = Writing.new
  end

  # GET /writings/1/edit
  def edit
  end

  # POST /writings
  # POST /writings.json
  def create
    @writing = Writing.new(writing_params)

    respond_to do |format|
      if @writing.save
        format.html { redirect_to @writing, notice: 'Writing was successfully created.' }
        format.json { render :show, status: :created, location: @writing }
      else
        format.html { render :new }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writings/1
  # PATCH/PUT /writings/1.json
  def update
    respond_to do |format|
      if @writing.update(writing_params)
        format.html { redirect_to @writing, notice: 'Writing was successfully updated.' }
        format.json { render :show, status: :ok, location: @writing }
      else
        format.html { render :edit }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writings/1
  # DELETE /writings/1.json
  def destroy
    @writing.destroy
    respond_to do |format|
      format.html { redirect_to writings_url, notice: 'Writing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writing
      @writing = Writing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def writing_params
      params.require(:writing).permit(:name, :title, :document)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/text_helper.rb
module TextHelper

end

app/helpers/writings_helper.rb
module WritingsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>writing.through.material</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class="wtm">
<div class="writing">
  <%= link_to 'http://meetingwords.com/Yvbpl4FuSU'  do %>
      <i class="fa fa-pencil" style="font-size: 2em; color: black;"></i>
  <% end %>
</div>

   <div class="a">a<br></div>

   <div class="aa">a<br></div>

   <div class="e">e<br></div>

   <div class="g">g<br></div>

   <div class="gg">g<br></div>

   <div class="h">h<br></div>

   <div class="hh">h<br></div>

   <div class="i">i<br></div>

   <div class="ii">i<br></div>

   <div class="iii">i<br></div>

   <div class="l">l<br></div>

   <div class="m">m<br></div>

   <div class="n">n<br></div>

   <div class="o">o<br></div>

   <div class="r">r<br></div>

   <div class="rr">r<br></div>

   <div class="rrr">r<br></div>

   <div class="t">t<br></div>

   <div class="tt">t<br></div>

   <div class="ttt">t<br></div>

   <div class="u">u<br></div>

   <div class="w">w<br></div>

   <div class="dot">
  <%= link_to '.', new_writing_path %><br></div>

   <div class="dotdot">
  <%= link_to '.', new_writing_path %><br></div>
</div>



   <%= yield %>

  </body>
</html>

app/views/text/text.html.erb
<% if @writings.present? %>
  <% @writings.reverse.each do |wr| %>
    <% if wr.document.content_type.start_with?("audio")%>
      <audio src=<%=url_for(wr.document)%> controls>  </audio>
    <% else %>
      <iframe source src= <%=url_for(wr.document)%> type="audio/mp3"
      width="700" height="1000" style="border: 0; padding-bottom: 10em;"></iframe>
    <% end %>
  <% end %>
<% end %>

app/views/writings/_form.html.erb
<%= form_with(model: writing, local: true) do |form| %>
  <% if writing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(writing.errors.count, "error") %> prohibited this writing from being saved:</h2>

      <ul>
        <% writing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :document %>
    <%= form.file_field :document %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/writings/edit.html.erb
<h1>Editing Writing</h1>

<%= render 'form', writing: @writing %>

<%= link_to 'Show', @writing %>&nbsp &nbsp |
<%= link_to 'Back', writings_path %>&nbsp &nbsp|
<%= link_to 'New Writing', new_writing_path %>&nbsp &nbsp|
<%= link_to 'All Texts', text_text_path %>&nbsp &nbsp|

app/views/writings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Writings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @writings.each do |writing| %>
      <tr>
        <td><%= writing.name %></td>
        <td><%= writing.title %></td>
        <td><%= link_to 'Show', writing %></td>
        <td><%= link_to 'Edit', edit_writing_path(writing) %></td>
        <td><%= link_to 'Destroy', writing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Writing', new_writing_path %> &nbsp &nbsp|
<%= link_to 'All Texts', text_text_path %>

app/views/writings/new.html.erb
<h1>New Writing</h1>

<%= render 'form', writing: @writing %>

<%= link_to 'Back', writings_path %>&nbsp &nbsp|
<%= link_to 'New Writing', new_writing_path %>&nbsp &nbsp|
<%= link_to 'All Texts', text_text_path %>

app/views/writings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @writing.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @writing.title %>
</p>

<iframe src=<%= url_for(@writing.document) if @writing.document.attached? %> width="700" height="780" style="border: none;"></iframe>
<br>

<%= link_to 'Edit', edit_writing_path(@writing) %>&nbsp &nbsp |
<%= link_to 'Back', writings_path %>&nbsp &nbsp|
<%= link_to 'New Writing', new_writing_path %>&nbsp &nbsp|
<%= link_to 'All Posts', text_text_path %>